[package]
name = "btech-rs"
version = "0.1.0"
edition = "2021"
default-run = "client"

[features]
debug = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = "0.14.2"
bevy-inspector-egui = {version = "0.27.0", optional = true}
hexx = "0.18.0"
rand = "0.8.5"
