[package]
name = "btech-rs"
version = "0.1.0"
edition = "2021"

[features]
debug = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = {version = "0.24.0", optional = true}
hexx = "0.17.0"
rand = "0.8.5"
