[package]
name = "btech-rs"
version = "0.1.0"
edition = "2021"
default-run = "client"

[features]
debug = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = "0.15.2"
bevy-inspector-egui = {version = "0.29.1", optional = true}
hexx = "0.20.0"
rand = "0.9.0"
